import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { chmodSync, copyFileSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, statSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("client generation does not touch the Nuxt HMR input when output is unchanged", async () => {
  const app = mkdtempSync(path.join(tmpdir(), "nstack-client-hmr-"));
  const fakeBin = path.join(app, "bin");
  const backendApi = path.join(app, "backend", "api");
  mkdirSync(path.join(app, "scripts"), { recursive: true });
  mkdirSync(path.join(app, "frontend", "app", "generated"), { recursive: true });
  mkdirSync(backendApi, { recursive: true });
  mkdirSync(fakeBin, { recursive: true });

  copyFileSync(
    path.join(repoRoot, "templates", "encore-nuxt", "scripts", "nstack-client.mjs"),
    path.join(app, "scripts", "nstack-client.mjs"),
  );
  writeFileSync(path.join(app, "backend", "encore.app"), `{"id":"hmr-test"}\n`);
  writeFileSync(path.join(backendApi, "status.ts"), "one\n");
  writeFakeEncore(path.join(fakeBin, "encore"));

  const env = { ...process.env, PATH: `${fakeBin}:${process.env.PATH || ""}` };
  const clientFile = path.join(app, "frontend", "app", "generated", "encore-client.ts");
  const appTempRoot = path.join(app, ".nstack", "tmp");
  const osTempBefore = osClientTempDirs();
  const runGen = () => execFileSync(process.execPath, ["scripts/nstack-client.mjs", "gen", "--force"], {
    cwd: app,
    env,
    stdio: "pipe",
  });
  const mtime = () => statSync(clientFile, { bigint: true }).mtimeNs;

  runGen();
  const first = mtime();
  assert.match(readFileSync(clientFile, "utf8"), /value = "one"/);

  await delay(25);
  runGen();
  const second = mtime();
  assert.equal(second, first);

  await delay(25);
  writeFileSync(path.join(backendApi, "status.ts"), "two\n");
  runGen();
  const third = mtime();
  assert.ok(third > second);
  assert.match(readFileSync(clientFile, "utf8"), /value = "two"/);
  assert.deepEqual(readDirNames(appTempRoot), []);
  assert.deepEqual(osClientTempDirs(), osTempBefore);

  const stale = path.join(appTempRoot, "client-stale");
  mkdirSync(stale, { recursive: true });
  const old = new Date(Date.now() - 2 * 60 * 60 * 1000);
  utimesSync(stale, old, old);
  runGen();
  assert.equal(existsSync(stale), false);
});

function writeFakeEncore(file) {
  writeFileSync(file, [
    "#!/usr/bin/env node",
    'const { mkdirSync, readFileSync, writeFileSync } = require("node:fs");',
    'const path = require("node:path");',
    "",
    "const args = process.argv.slice(2);",
    'if (args[0] === "version") {',
    '  console.log("encore version v0.0.0-test");',
    "  process.exit(0);",
    "}",
    'if (args[0] === "check") process.exit(0);',
    'if (args[0] === "gen" && args[1] === "client") {',
    '  const output = args[args.indexOf("--output") + 1];',
    '  const status = readFileSync(path.join(process.cwd(), "api", "status.ts"), "utf8").includes("two") ? "two" : "one";',
    "  mkdirSync(path.dirname(output), { recursive: true });",
    "  writeFileSync(output, [",
    '    "// Code generated by fake Encore. DO NOT EDIT.\\n",',
    '    "export type BaseURL = string\\n",',
    '    "export const Local: BaseURL = \\"http://localhost:4000\\"\\n",',
    '    "/**\\n",',
    '    " * Environment returns a BaseURL for calling the Encore application\'s API in the given environment.\\n",',
    '    " */\\n",',
    '    "export function Environment(name: string): BaseURL {\\n",',
    '    "    return \\"https://\\" + name + \\".encr.app\\"\\n",',
    '    "}\\n",',
    '    "\\n",',
    '    "/**\\n",',
    '    " * PreviewEnv returns a BaseURL for calling the Encore application\'s API in the given preview environment.\\n",',
    '    " */\\n",',
    '    "export function PreviewEnv(pr: number | string): BaseURL {\\n",',
    '    "    return Environment(`pr${pr}`)\\n",',
    '    "}\\n",',
    '    "export default class Client { public readonly value = \\"" + status + "\\" }\\n",',
    '  ].join(""));',
    "  process.exit(0);",
    "}",
    'console.error("unexpected fake encore args: " + args.join(" "));',
    "process.exit(1);",
    "",
  ].join("\n"));
  chmodSync(file, 0o755);
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function readDirNames(dir) {
  return existsSync(dir) ? readdirSync(dir).sort() : [];
}

function osClientTempDirs() {
  return readdirSync(tmpdir())
    .filter((name) => /^nstack-client(?:-check|-bench)?-/.test(name))
    .sort();
}
