import { stringifyYaml } from "./yaml.js";

export function renderDokployCompose(ctx) {
  const { config, resources, images = {}, release, build = null } = ctx;
  const doc = {
    name: config.app.slug,
    services: {
      frontend: {
        ...serviceImageOrBuild("frontend", { config, release, image: images.frontend, build }),
        restart: "unless-stopped",
        environment: {
          NODE_ENV: "production",
          HOST: "0.0.0.0",
          PORT: "3000",
          NITRO_HOST: "0.0.0.0",
          NITRO_PORT: "3000",
          NUXT_PUBLIC_API_BASE_URL: "/api",
          NUXT_API_SERVER_BASE_URL: "http://backend:8080",
          NUXT_API_INTERNAL_BASE_URL: "http://backend:8080",
          NSTACK_APP_SLUG: config.app.slug,
          NSTACK_GIT_COMMIT: "${NSTACK_GIT_COMMIT:-local}",
          NSTACK_IMAGE_TAG: "${NSTACK_IMAGE_TAG:-local}",
        },
        expose: ["3000"],
        depends_on: {
          backend: { condition: "service_started" },
        },
      },
      backend: {
        ...serviceImageOrBuild("backend", { config, release, image: images.backend, build }),
        restart: "unless-stopped",
        environment: backendEnv(ctx),
        expose: ["8080"],
        healthcheck: {
          test: ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:8080/__encore/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""],
          interval: "15s",
          timeout: "5s",
          retries: 8,
          start_period: "30s",
        },
        depends_on: backendDependsOn(resources),
      },
    },
  };

  if (resources.topics.length > 0) {
    doc.services.nsqlookupd = {
      image: "nsqio/nsq:v1.3.0",
      restart: "unless-stopped",
      command: "/nsqlookupd",
      expose: ["4160", "4161"],
    };
    doc.services.nsqd = {
      image: "nsqio/nsq:v1.3.0",
      restart: "unless-stopped",
      command: "/nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd --data-path=/data",
      volumes: ["nsq_data:/data"],
      expose: ["4150", "4151"],
      depends_on: {
        nsqlookupd: { condition: "service_started" },
      },
    };
    doc.volumes = { nsq_data: {} };
  }

  return `# Generated by nstack. Ingress is managed by Dokploy Domains/Traefik, not by a proxy container.
${stringifyYaml(doc)}`;
}

function serviceImageOrBuild(name, { config, release, image, build }) {
  if (!build) return { image };
  const service = build.services?.[name];
  const localImage = `${config.app.slug}-${name}:\${NSTACK_IMAGE_TAG:-local}`;
  return {
    image: service?.image || localImage,
    pull_policy: "build",
    build: {
      context: build.context,
      dockerfile: service?.dockerfile,
      ...(config.deploy.platform ? { platforms: [config.deploy.platform] } : {}),
      ...(service?.args ? { args: service.args } : {}),
    },
  };
}

function backendEnv(ctx) {
  const { config, resources } = ctx;
  const env = {
    PORT: "8080",
    NODE_ENV: "production",
    APP_ID: config.app.slug,
    APP_VERSION: "${NSTACK_GIT_COMMIT:-local}",
    GIT_COMMIT: "${NSTACK_GIT_COMMIT:-local}",
    IMAGE_TAG: "${NSTACK_IMAGE_TAG:-local}",
    NSTACK_TARGET: config.deploy.target,
    NSTACK_DOMAIN: config.app.domain,
  };
  if (resources.databases.length > 0) {
    env.NSTACK_POSTGRES_PASSWORD = "${NSTACK_POSTGRES_PASSWORD:?set NSTACK_POSTGRES_PASSWORD}";
  }
  if (resources.caches.length > 0) {
    env.NSTACK_REDIS_PASSWORD = "${NSTACK_REDIS_PASSWORD:?set NSTACK_REDIS_PASSWORD}";
  }
  for (const secret of resources.secrets) {
    env[secret] = `\${${secret}:?set ${secret}}`;
  }
  return env;
}

function backendDependsOn(resources) {
  if (resources.topics.length === 0) return undefined;
  return { nsqd: { condition: "service_started" } };
}
