import { objectStorageBucketName } from "../resource-names.js";
import { stringifyYaml } from "./yaml.js";

export function renderDokployCompose(ctx) {
  const { config, images = {}, release, build = null } = ctx;
  const resources = normalizeResources(ctx.resources);
  const renderCtx = { ...ctx, resources };
  const backendHost = `${config.app.slug}-backend`;
  const minioHost = `${config.app.slug}-minio`;
  const nsqdHost = `${config.app.slug}-nsqd`;
  const nsqlookupdHost = `${config.app.slug}-nsqlookupd`;
  const doc = {
    name: config.app.slug,
    services: {
      frontend: {
        ...serviceImageOrBuild("frontend", { config, release, image: images.frontend, build }),
        restart: "unless-stopped",
        environment: {
          NODE_ENV: "production",
          HOST: "0.0.0.0",
          PORT: "3000",
          NITRO_HOST: "0.0.0.0",
          NITRO_PORT: "3000",
          NUXT_PUBLIC_API_BASE_URL: "/api",
          NUXT_API_SERVER_BASE_URL: `http://${backendHost}:8080`,
          NUXT_API_INTERNAL_BASE_URL: `http://${backendHost}:8080`,
          NSTACK_APP_SLUG: config.app.slug,
          NSTACK_BACKEND_HOST: backendHost,
          NSTACK_GIT_COMMIT: "${NSTACK_GIT_COMMIT:-local}",
          NSTACK_IMAGE_TAG: "${NSTACK_IMAGE_TAG:-local}",
        },
        expose: ["3000"],
        depends_on: {
          backend: { condition: "service_started" },
        },
      },
      backend: {
        ...serviceImageOrBuild("backend", { config, release, image: images.backend, build }),
        restart: "unless-stopped",
        environment: backendEnv(renderCtx),
        expose: ["8080"],
        networks: {
          default: {
            aliases: [backendHost],
          },
        },
        healthcheck: {
          test: ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:8080/__encore/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""],
          interval: "15s",
          timeout: "5s",
          retries: 8,
          start_period: "30s",
        },
        depends_on: backendDependsOn(resources),
      },
    },
  };

  if (resources.topics.length > 0) {
    doc.services.nsqlookupd = {
      image: "nsqio/nsq:v1.3.0",
      restart: "unless-stopped",
      command: "/nsqlookupd",
      expose: ["4160", "4161"],
      networks: {
        default: {
          aliases: [nsqlookupdHost],
        },
      },
    };
    doc.services.nsqd = {
      image: "nsqio/nsq:v1.3.0",
      restart: "unless-stopped",
      command: `/nsqd --lookupd-tcp-address=${nsqlookupdHost}:4160 --broadcast-address=${nsqdHost} --data-path=/data`,
      volumes: ["nsq_data:/data"],
      expose: ["4150", "4151"],
      networks: {
        default: {
          aliases: [nsqdHost],
        },
      },
      depends_on: {
        nsqlookupd: { condition: "service_started" },
      },
    };
    doc.volumes = { ...(doc.volumes || {}), nsq_data: {} };
  }

  if (resources.buckets.length > 0) {
    doc.services.minio = {
      image: "minio/minio:latest",
      restart: "unless-stopped",
      command: "server /data --address :9000 --console-address :9001",
      environment: {
        MINIO_ROOT_USER: "${NSTACK_MINIO_ACCESS_KEY:?set NSTACK_MINIO_ACCESS_KEY}",
        MINIO_ROOT_PASSWORD: "${NSTACK_MINIO_SECRET_KEY:?set NSTACK_MINIO_SECRET_KEY}",
      },
      volumes: ["minio_data:/data"],
      expose: ["9000"],
      networks: {
        default: {
          aliases: [minioHost],
        },
      },
      healthcheck: {
        test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/minio/health/live >/dev/null"],
        interval: "10s",
        timeout: "5s",
        retries: 12,
        start_period: "10s",
      },
    };
    doc.services["minio-init"] = {
      image: "minio/mc:latest",
      restart: "no",
      environment: {
        MINIO_ROOT_USER: "${NSTACK_MINIO_ACCESS_KEY:?set NSTACK_MINIO_ACCESS_KEY}",
        MINIO_ROOT_PASSWORD: "${NSTACK_MINIO_SECRET_KEY:?set NSTACK_MINIO_SECRET_KEY}",
      },
      entrypoint: ["/bin/sh", "-c"],
      command: minioInitScript(config, resources.buckets, minioHost),
      depends_on: {
        minio: { condition: "service_healthy" },
      },
    };
    doc.services.backend.depends_on = {
      ...(doc.services.backend.depends_on || {}),
      minio: { condition: "service_started" },
    };
    doc.volumes = { ...(doc.volumes || {}), minio_data: {} };
  }

  return `# Generated by nstack. Ingress is managed by Dokploy Domains/Traefik, not by a proxy container.
${stringifyYaml(doc)}`;
}

function serviceImageOrBuild(name, { config, release, image, build }) {
  if (!build) return { image };
  const service = build.services?.[name];
  const localImage = `${config.app.slug}-${name}:\${NSTACK_IMAGE_TAG:-local}`;
  return {
    image: service?.image || localImage,
    pull_policy: "build",
    build: {
      context: build.context,
      dockerfile: service?.dockerfile,
      ...(config.deploy.platform ? { platforms: [config.deploy.platform] } : {}),
      ...(service?.args ? { args: service.args } : {}),
    },
  };
}

function normalizeResources(resources = {}) {
  return {
    databases: [],
    caches: [],
    topics: [],
    buckets: [],
    secrets: [],
    crons: [],
    ...resources,
  };
}

function backendEnv(ctx) {
  const { config, resources } = ctx;
  const env = {
    PORT: "8080",
    NODE_ENV: "production",
    APP_ID: config.app.slug,
    APP_VERSION: "${NSTACK_GIT_COMMIT:-local}",
    GIT_COMMIT: "${NSTACK_GIT_COMMIT:-local}",
    IMAGE_TAG: "${NSTACK_IMAGE_TAG:-local}",
    NSTACK_TARGET: config.deploy.target,
    NSTACK_DOMAIN: config.app.domain,
  };
  if (resources.databases.length > 0) {
    env.NSTACK_POSTGRES_PASSWORD = "${NSTACK_POSTGRES_PASSWORD:?set NSTACK_POSTGRES_PASSWORD}";
  }
  if (resources.caches.length > 0) {
    env.NSTACK_REDIS_PASSWORD = "${NSTACK_REDIS_PASSWORD:?set NSTACK_REDIS_PASSWORD}";
  }
  if (resources.buckets.length > 0) {
    env.NSTACK_MINIO_ACCESS_KEY = "${NSTACK_MINIO_ACCESS_KEY:?set NSTACK_MINIO_ACCESS_KEY}";
    env.NSTACK_MINIO_SECRET_KEY = "${NSTACK_MINIO_SECRET_KEY:?set NSTACK_MINIO_SECRET_KEY}";
  }
  for (const secret of resources.secrets) {
    env[secret] = `\${${secret}:?set ${secret}}`;
  }
  return env;
}

function backendDependsOn(resources) {
  const deps = {};
  if (resources.topics.length > 0) deps.nsqd = { condition: "service_started" };
  return Object.keys(deps).length ? deps : undefined;
}

function minioInitScript(config, buckets, minioHost) {
  const commands = [
    `until mc alias set local http://${minioHost}:9000 "${composeRuntimeEnv("MINIO_ROOT_USER")}" "${composeRuntimeEnv("MINIO_ROOT_PASSWORD")}"; do sleep 1; done`,
    ...buckets.map((bucket) => `mc mb --ignore-existing local/${objectStorageBucketName(config.app.slug, bucket)}`),
    ...buckets
      .filter((bucket) => bucket.public)
      .map((bucket) => `mc anonymous set download local/${objectStorageBucketName(config.app.slug, bucket)}`),
  ];
  return commands.join(" && ");
}

function composeRuntimeEnv(name) {
  return `$$` + `{${name}}`;
}
